# Generated by Django 5.0.7 on 2024-09-16 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان ')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='عکس ')),
                ('discription', models.TextField(verbose_name='توضیحات')),
                ('status', models.BooleanField(default=False)),
                ('counted_view', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('published_date', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': 'خدمات',
                'verbose_name_plural': ' خدمات  ها',
            },
        ),
    ]
