# Generated by Django 5.0.7 on 2024-09-16 13:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0002_remove_service_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='director',
            field=models.TextField(blank=True, null=True, verbose_name='مجری طرح'),
        ),
    ]
