# Generated by Django 5.0.7 on 2024-09-17 05:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_director'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderWork',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان ')),
                ('discription', models.TextField(verbose_name='توضیحات')),
                ('work', models.CharField(choices=[('طراحی سایت با جنگو ', 'طراحی سایت با جنگو '), ('طراحی سایت با ورپرس ', 'طراحی سایت با ورپرس '), ('طراحی گرافیکی با فتوشاپ ', 'طراحی گرافیکی با فتوشاپ ')], default=None, max_length=255)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'سفارش',
                'verbose_name_plural': 'لیست سفارش ها',
            },
        ),
    ]
