# Generated by Django 5.0.7 on 2024-09-17 05:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_orderwork'),
    ]

    operations = [
        migrations.DeleteModel(
            name='OrderWork',
        ),
    ]
