# Generated by Django 5.0.7 on 2024-09-17 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0006_orderwork'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderwork',
            name='work',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
