# Generated by Django 5.0.7 on 2024-09-14 03:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OTP',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.BigIntegerField(default=1, null=True)),
                ('code', models.BigIntegerField(default=1, null=True)),
                ('created_at', models.DateTimeField(auto_now=True, verbose_name='تاریخ اضافه شدن')),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'otp',
                'verbose_name_plural': 'opts',
            },
        ),
    ]
