# Generated by Django 5.0.7 on 2024-09-14 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_otp'),
    ]

    operations = [
        migrations.AddField(
            model_name='otp',
            name='password',
            field=models.CharField(max_length=200, null=True, verbose_name='رمز کاربر'),
        ),
        migrations.AddField(
            model_name='otp',
            name='token',
            field=models.CharField(max_length=200, null=True, verbose_name='توکن کاربر'),
        ),
    ]
