# Generated by Django 5.0.7 on 2024-09-14 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_otp_password_otp_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otp',
            name='phone',
            field=models.CharField(blank=True, max_length=30, null=True),
        ),
    ]
