# Generated by Django 5.0.7 on 2024-09-21 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_course_free_course_image_course_percent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='course',
            name='percent',
        ),
        migrations.AddField(
            model_name='course',
            name='price_percented',
            field=models.BigIntegerField(default=0),
        ),
    ]
