# Generated by Django 5.0.7 on 2024-09-18 12:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='WorkField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('disctption', models.TextField()),
            ],
            options={
                'verbose_name': ' زمینه فعالیت  ',
                'verbose_name_plural': '  زمینه فعالیت ها ',
            },
        ),
        migrations.CreateModel(
            name='TeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('phone', models.BigIntegerField(default=0)),
                ('email', models.EmailField(max_length=254)),
                ('disctption', models.TextField()),
                ('image', models.ImageField(upload_to='team/')),
                ('status', models.BooleanField(default=False)),
                ('counted_view', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('published_date', models.DateTimeField(null=True)),
                ('work', models.ManyToManyField(to='about.workfield')),
            ],
            options={
                'verbose_name': 'عضو تیم ',
                'verbose_name_plural': 'اعضای تیم ',
                'ordering': ['created_date'],
            },
        ),
    ]
