# Generated by Django 5.0.7 on 2024-09-18 12:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TeamMember',
        ),
        migrations.DeleteModel(
            name='WorkField',
        ),
    ]
