# Generated by Django 5.0.7 on 2024-10-09 12:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_subscribe'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Subscribe',
        ),
    ]
