# Generated by Django 5.0.7 on 2024-09-14 13:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'دسته بندی ',
                'verbose_name_plural': 'دسته بندی ها',
            },
        ),
        migrations.CreateModel(
            name='Work',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='عنوان کار')),
                ('image', models.ImageField(blank=True, null=True, upload_to='works/', verbose_name='عکس کار')),
                ('discription', models.TextField(verbose_name='توضیحات')),
                ('discription2', models.TextField(blank=True, null=True, verbose_name='توضیحات 2 ')),
                ('address', models.TextField(blank=True, null=True, verbose_name='ادرس سایت ')),
                ('director', models.TextField(verbose_name='مجری طرح')),
                ('status', models.BooleanField(default=False)),
                ('counted_view', models.IntegerField(default=0)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('published_date', models.DateTimeField(null=True)),
                ('category', models.ManyToManyField(to='exampleworks.category')),
            ],
            options={
                'verbose_name': 'پست ',
                'verbose_name_plural': 'پست ها ',
                'ordering': ['created_date'],
            },
        ),
    ]
