# Generated by Django 5.0.7 on 2024-10-09 04:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exampleworks', '0002_alter_work_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('allow', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_date', models.DateTimeField(auto_now=True, null=True)),
                ('work', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='exampleworks.work')),
            ],
            options={
                'verbose_name': 'گامنت',
                'verbose_name_plural': 'کامنت ها ',
            },
        ),
    ]
